version: "3.3"

services:
#   db:
#     image: postgres
#     volumes:
#       - ./tmp/db:/var/lib/postgresql/data
#     environment:
#       POSTGRES_PASSWORD: password
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    # depends_on:
    #   - db
    ports: 
      - "3000:3000"
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    env_file: .env
    environment:
      RAILS_ENV: production
  # frontend:
  #   image: "node:16.13.2-alpine"
  #   working_dir: /app
  #   volumes:
  #     - ./reactapp:/app
  #   ports:
  #     - "3000:3000"
  #   command: "yarn start"
  #   depends_on:
  #     - backend      

volumes:
  gem_cache:
  # db_data:
  # node_modules:   