version: "3.3"
services:
  # db:
  #   image: postgres
  #   volumes:
  #     - ./tmp/db:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_PASSWORD: password
  # backend:
  #   build: .
  #   command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
  #   volumes:
  #     - .:/rails7react-docker
  #   ports:
  #     - "3001:3001"
  #   depends_on:
  #     - db
  frontend:
    build:
      context: ./reactapp
      dockerfile: Dockerfile
    environment:
      CHOKIDAR_USEPOLLING: "true"   
    working_dir: /app
    volumes:
      - /app/node_modules
      - ./reactapp:/app
    ports:
      - "3000:3000"
    command: "yarn start"
    # depends_on:
    #   - backend